
help = """
>addr <stat here>|help

Options for <stat here>

maxhp|hp|max hp
maxmp|mp|max mp
ampr
crit|critrate|critical rate|crate|crit rate
acc|accuracy
dodge
agi
dex
int
vit
str
atk
watk|weaponatk|weapon atk
matk
fractional barrier|fbar|fbarrier
magic barrier|mbar|mbarrier
physical barrier|pbar|pbarrier
magic resistance|mres|mresist
physical resistance|pres|presist
def
mdef
+aggro|+agg|aggro|agg
-aggro|-agg
dtedark|dtdark|dte dark
dteearth|dtearth|dte earth
dtelight|dtlight|dte light
dtewater|dtwater|dte water
dtewind|dtwind|dte wind
dtefire|dtfire|dte fire
dteneutral|dtneutral|dte neutral|dteneut|dte neut
rtedark|rtdark|rte dark|darkres|darkresist
rteearth|rtearth|rte earth|earthres|earthresist
rtefire|rtfire|rte fire|fireres|fireresist
rtelight|rtlight|rte light|lightres|lightresist
rtewind|rtwind|rte wind|windres|windresist
rtewater|rtwater|rte water|waterres|waterresist
drop|droprate|drop rate
exp|expgain|exp gain
"""




[food_buffs.max_mp]

text = """
*Food Addresses for Ankake Fried Rice (MaxMP)*

*Level 10*
1010216 - Salmonella
1011212 - Epiey!!
1020808 - ã‚³ã‚³ãƒ«ãƒ«
1027777 - Aka Shiro
2010510 - Ultimateã‚ã‚“ã‚ã‚“
2020101 - Paracetamol
3017676 - yuxieyoko
3204544 - Amatsuka Kirin
4261111 - maruna
6053838 - æœ‹@
7100720 - Juda
7150029 - ORCA29
"""



[food_buffs.max_hp]

text = """
*Food Addresses for Golden Stir Fry (MaxHP)*

*Level 10*
1010032 - â˜…ç©ºçŒ«
1010084 - ã‚ãã‚‰
1010356 - ã‚‰ã„ã‚€03
1250015 - é›ªå³¶ã„ã¡ã”
2010228 - ~ã‚·ãƒ¥ã‚·ãƒ¥~
3090618 - snow618
3092003 - â— Rikkaâ¤ â–·
3191130 - Kail NW
3260178 - maluth
4262222 - mashilo
54154629 - ã‚·ãƒ£ãƒ«ãƒ 
6010062 - G - Thunder (JPN)
6199999 - garun1
"""



[food_buffs.attack_mp_recovery]

text = """
*Food Addresses for Yakisoba (AMPR)*

*Level 10*
1010017 - í‰ì˜¨í•œë‚ 
1010596 - å†·Hiroâ˜†
1011010 - 0 kara
1023040 - Quinone (K)
1047777 - ~Zeref~
1111000 - ã‚«ãƒ³ã‚³ã‚¦
3020777 - ç™½æœ€ä¸­
3201003 - ã€ K E R R Y ã€
4040404 - S A R A
4206969 - xenesis5
4233333 - AlvinXxX
5236969 - é»’æ¾¤ã‚¿ã‚¤ã‚¢
7069420 - ğŸ‘‰ * Garu * ğŸ‘ˆ
7088807 - @Ray
7220777 - Veny
8120000 - Lamlo
"""


[food_buffs.critical_rate]
text = """
*Food Addresses for Takoyaki (Critical Rate)*

*Level 10*
1037777 - Hati Hervor
1100000 - I n u G a m i â€¢
1181140 - ã‚‰ã‚“ãª
2022020 - #SAM#
3010777 - ã‚ã‚“ã€€â€¢ã€€ã«ã‚„ãƒ¼
3030159 - Lauryn_
3149696 - NoiR
4010000 - ä¿ºãŒé’å¨¥æ§˜
5119105 - - Kanna -
6021230 - â˜†ï¼°ï½‰ï½ï½â˜†
7162029 - Player20
"""

[food_buffs.accuracy]

text = """
*Food Addresses for Shoyu Ramen (Accuracy)*

*Level 10*
2010308 - @alpha
4261111 - maruna

*Level 9*
1181220 - æ¢¨èŠ±
7160030 - ã‚µãƒ¼ãƒ™ã‚¤
"""


[food_buffs.dodge]

text = """
*Food Addresses for Shio Ramen (Dodge)*

*Level 7*
2020808 - Ectoplasm
"""


[food_buffs.agi]

text = """
*Food Addresses for Mentaiko Rice Ball (AGI)*

*Level 10*
1220777 - ã‚µã‚¹ã‚±U^ã‚§^U
2020037 - Mana-T
4262222 - mashilo
7162029 - Player20

*Level 9*
1110033 - ãã‚Šã¼ãƒ¼â˜†
6269999 - é…’å‘‘
"""


[food_buffs.dex]

text = """
*Food Addresses for Salmon Rice Ball (DEX)*

*Level 10*
1010058 - Â· H20 Â·
1010106 - Yoku'
1010261 - ã‚¤ã‚°ãƒ«ãƒ¼
1074649 - âˆ® ãƒãƒã‚¡ âˆ®
1112220 - Kiraraâ™¥
2020222 - Himura Oza
3111999 - Espur
3220777 - â˜†ã‚¨ãƒˆãƒ¯ãƒ¼ãƒ«â˜†
7011001 - ã€MBã€‘ VolTâ€¾ã¸å‡¸
7140777 - Aurianne
"""

[food_buffs.int]

text = """
*Food Addresses for Umeboshi Rice Ball (INT)*

*Level 10*
1010140 - ã‹ãŒã‚Š
1010498 - æ¡ƒå¤
1032222 - Shyturu
1047777 - ~Zeref~
2020707 - Ascorbic Acid
5190001 - ã‚·ã‚§ãƒªã‚¢.
6010701 - ramenEso
7130001 - @ã¿ã’ã‚‹
"""

[food_buffs.vit]

text = """
*Food Addresses for Tuna Mayo Rice Ball (VIT)*

*Level 10*
4032850 - Aphrodite tiger
"""


[food_buffs.str]

text = """
*Food Addresses for Okaka Rice Ball (STR)*

*Level 10*
1010055 - Echidna@
1010968 - ã‚¢ã‚¸ãƒ¤
1011069 - A J I
1110033 - ãã‚Šã¼ãƒ¼â˜†
2017890 - ã¿ã•ã*
2020303 - Amanita
2180000 - Ryopin
4010024 - ã„ãã‚‹ã‚“
5261919 - ãƒ«ãƒ¼ã‚¸ã‚¢ãƒ«
7070777 - -Xen-
"""


[food_buffs.atk]

text = """
*Food Addresses for Pizza Diavola (ATK)*

*Level 10*
7170717 - Isuniâ˜†
1119876 - ã‚­ãƒ…ãƒ„
6010024 - ã€ G a p a p a ã€
1011126 - ãƒ¾feryanz
1010810 - å¤œãƒˆyatoâ˜†
1011122 - ãƒ™ãƒƒã‚­ãƒ¼
4240242 - Nakean
7050301 - Keith
6269999 - é…’å‘‘
5110834 - åŠ å¯¿è‘‰
3259040 - é›ªç¾½
3180777 - Reonâˆ®
2020404 - HbA1c
3010777 - ã‚ã‚“ â€¢ ã«ã‚„ãƒ¼
4170999 - ãŠã‚Šã´
1067777 - YusagKurumi
1180020 - Rouen

*Level 8*
2222226 - Aura Bella Fiora
"""



[food_buffs.weapon_atk]

text = """
*Food Addresses for Pizza Margherita (Weapon ATK)*

*Level 10*
1010810 - å¤œãƒˆyatoâ˜†
1011122 - ãƒ™ãƒƒã‚­ãƒ¼
1011126 - ãƒ¾feryanz
1067777 - YusagKurumi
1180020 - Rouen
1200020 - ãƒ†ã‚£ãƒ¼ã‚¯
2020404 - HbA1c
3010777 - ã‚ã‚“ã€€â€¢ã€€ã«ã‚„ãƒ¼
3180777 - Reonâˆ®
4170999 - ãŠã‚Šã´
4240242 - Nakean
5110834 - åŠ å¯¿è‘‰
6010024 - ã€ G a p a p a ã€
6130623 - é›ªç¾½
6269999 - é…’å‘‘
7050301 - Keith
"""


[food_buffs.matk]

text = """
Not available for now
"""


[food_buffs.fractional_barrier]
text = """
Not available for now
"""

[food_buffs.magic_barrier]
text = """
Not available for now
"""

[food_buffs.physical_barrier]
text = """
Not available for now
"""

[food_buffs.magic_resistance]
text = """
*Food Addresses for Fish Burger (Magic Resistance%)*

*Level 10*
1111575 - Kiyanh
1181220 - æ¢¨èŠ±
2020505 - Niacin (B3)
5200025 - ãŸã¤çŒ«â˜†
6190007 - nanakoâ™ª
7010016 - Lianæˆ€
8010016 - Â° Roulecca
"""

[food_buffs.physical_resistance]
text = """
*Food Addresses for Beef Burger (Physical Resistance%)*

*Level 10*
1010081 - Kawasaki
1020001 - ã¦ã‚“ã’ã‚“
1231776 - xxxdsmer
2020111 - L. casei
2020345 - - C H A R M Z â˜…
2200117 - ã—ã„ã½
4010051 - ãƒã‚°ãƒŠ
6010701 - ramenEso
"""

[food_buffs.def]
text = """
Not available for now
"""

[food_buffs.mdef]
text = """
Not available for now
"""

[food_buffs.aggro]
text = """
Food Addresses for Beef Stew (Aggro%)

*Level 10*
1010207 - Pew_Pew
1130832 - å’²æ„›"
1140002 - Neaki
2020606 - Biotin
3053131 - DaoNaga
3158668 - VoidWolf
4220777 - æ˜¥å§«â¤
5261002 - ãƒãƒ³ãƒ¢ã‚¹ãƒãƒ³

*Level 9*
2010136 - S y n å½¡

*Level 8*
3204544 (Amatsuka Kirin)
"""

[food_buffs.negative_aggro]
text = """
*Food Addresses for White Stew (-Aggro%)*

*Level 10*
1010038 - dara
1010147 - í„°ëƒ
1010261 - ã‚¤ã‚°ãƒ«ãƒ¼
2020808 - Ectoplasm
3190038 - â˜†ã‚«ãƒ¼ãƒŸãƒ©â˜…
"""

[food_buffs.damage_to_dark]
text = """
*Food Addresses for Squid Ink Pasta (Damage to Dark%)*

*Level 10*
2130776 - ã‚µãƒˆãƒªãƒ¼ãƒ«
6116116 - (â­—â–³â­—)
1190020 - ãƒãƒ¥ãƒ¬ @è¿·è·¯å±‹

*Level 9*
5010092 - Who's Wo
"""

[food_buffs.damage_to_earth]
text = """
*Food Addresses for Genovese (Damage to Earth%)*

*Level 10*
2020202 - S A R A

*Level 9*
1011001 - S i r F a t h
4233333 - AlvinXxX
7100666 - itspaez

*Level 8*
1010216 - Salmonella
"""

[food_buffs.damage_to_light]
text = """
*Food Addresses for Carbonara (Damage to Light%)*

*Level 9*
1020345 - Death Â· Gun

*Level 8*
3111999 - Espur
"""

[food_buffs.damage_to_water]
text = """
*Food Addresses for Vongole (Damage to Water%)*

*Level 10*
1110111 - S A R A
3210100 - â™§æ°´ã®ã†ãŸ
7150030 - ãƒ•ã‚¡ãƒ¬

*Level 9*
7011001 - ã€MBã€‘ VolTâ€¾ã¸å‡¸
"""

[food_buffs.damage_to_wind]
text = """
*Food Addresses for Naporitan (Damage to Wind%)*

*Level 10*
3030303 - S A R A
"""

[food_buffs.damage_to_fire]
text = """
*Food Addresses for Bolognese (Damage to Fire%)*

*Level 10*
3210106 - â™§ç«ã®ã†ãŸ

*Level 9*
1121212 - RioCakra
7088807 - @Ray
9181111 - #Ryopin#

*Level 7*
8120000 - Lamlo
"""

[food_buffs.damage_to_neutral]
text = """
Not available for now
"""

[food_buffs.dark_resistance]
text = """
Not available for now
"""

[food_buffs.earth_resistance]
text = """
Not available for now
"""

[food_buffs.fire_resistance]
text = """
Not available for now
"""

[food_buffs.light_resistance]
text = """
Not available for now
"""

[food_buffs.wind_resistance]
text = """
Not available for now
"""

[food_buffs.neutral_resistance]
text = """
Not available for now
"""

[food_buffs.water_resistance]
text = """
Not available for now
"""

[food_buffs.drop_rate]
text = """
Not available for now
"""

[food_buffs.exp_gain]
text = """
Not available for now
"""
